### ISSUE TITLE
MQ Version 8.0.0.4

### ISSUE THREAD

**Issue by Norbert-Pfister** [ibm-messaging/mq-mqsc-editor-plugin#1]
Since i upgraded my MQ from Version 8.0.0.2 to Version 8.0.0.4
this plugin does not work anymore in MQ Explorer.
It is nowhere to be seen even afer a new dropin

**Comment by jefflowrey** [comment]
Hi -

There are two possible causes:  1) The fixpack installer removed MS0S entirely OR 2) The plugin/feature cache needs to be reloaded. 

To figure out which one, launch MQExplorer and go to the Help menu, and select "About Websphere MQ Explorer".  Then click on "Installation Details".  You should see MS0S listed in the first pane.  If not, double-check the features pane. 

If neither of those show MS0S, then it needs to be reinstalled.

If at least one of those shows MS0S, then the cache needs to be reloaded.  Exit MQExplorer, and then from a command prompt enter "mqexplorer -clean".

**Comment by Norbert-Pfister** [comment]
Jeff, thank you for the immediate response.
MS0S was still in the repository as shown in the installation details.
I finally could fully uninstall it and did the "mqexplorer -clean" afterwards.
Simply providing MS0S in the dropins dir didn't help , so i manually installed it by: 
Install new software - Add - Archive - choose dropins\MS0S\mq-mqsc-editor-plugin-master\ship\MQSCEditor1.7.0.0ArchiveSite.zip .
There MS0S was choosable.
