### ISSUE TITLE
Won't install on MQ9 Explorer

### ISSUE THREAD

**Issue by req24028** [ibm-messaging/mq-mqsc-editor-plugin#2]
Is there any chance on getting a new release that might install on a MQ9 Explorer as the plugin is very beneficial but I can't get it to work on the MQ9Explorer with either the dropin option or the install process.  The explorer just ignores the dropin version and doesn't show up.

**Comment by ibmmqmet** [comment]
Since the original author is no longer dealing with this repository, I've just created a new version that appears to be compatible with MQ V9.

**Comment by req24028** [comment]
Thank you, thank you, thank you.  I just downloaded it and added it to my MQExplorer as a drop-in site and it works perfectly.  You are the greatest!!!!
